### ISSUE TITLE
Add audit log for mock management

### ISSUE THREAD

**Issue by neel1996** [arbindo/mimock#127]
<a href="https://github.com/neel1996"><img src="https://avatars.githubusercontent.com/u/47709856?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [neel1996](https://github.com/neel1996)**
_Saturday Feb 12, 2022 at 12:39 GMT_
_Originally opened as https://github.com/neel1996/mimock/issues/29_

----

An audit table to log the list of operations performed by an user on the existing mocks

**Comment by aravinve** [comment]
Completed
