### ISSUE TITLE
[UI] Check and improve test coverage

### ISSUE THREAD

**Issue by aravinve** [arbindo/mimock#162]
The test coverage is significantly less for the UI layer.
We need to improve and add more tests.

src/components/mockManagement/MockDetails |   | 38.57% | 27/70 | 10% | 1/10 | 15.78% | 3/19 | 38.57% | 27/70
-- | -- | -- | -- | -- | -- | -- | -- | -- | --
src/components/dashboard/ContentArea/Sidebar |   | 51% | 51/100 | 30% | 3/10 | 38.46% | 10/26 | 52.04% | 51/98
src/utils |   | 51.35% | 19/37 | 35.71% | 5/14 | 100% | 3/3 | 51.35% | 19/37
src/components/dashboard/Toolbar |   | 52.54% | 31/59 | 8.33% | 1/12 | 80% | 4/5 | 52.54% | 31/59
src/components/dashboard |   | 53.06% | 26/49 | 0% | 0/2 | 28.57% | 4/14 | 53.06% | 26/49
src/components/dashboard/ContentArea/List |   | 53.7% | 29/54 | 10% | 3/30 | 20% | 2/10 | 54.71% | 29/53
src/components/mockManagement/MockDetails/detailcontentviewer |   | 58.33% | 21/36 | 18.75% | 6/32 | 75% | 3/4 | 58.33% | 21/36
src/hooks |   | 61.29% | 38/62 | 67.64% | 23/34 | 66.66% | 6/9 | 61.29% | 38/62
src/components/settings/PlatformSettings |   | 62.5% | 25/40 | 20% | 4/20 | 27.27% | 3/11 | 62.5% | 25/40
src/components/mockManagement/MockDetails/detailcontentviewer/ResponsePane |   | 78.94% | 15/19 | 0% | 0/2 | 66.66% | 2/3 | 78.94% | 15/19
src/api/services/mockManagement |   | 79.03% | 49/62 | 61.36% | 27/44 | 95% | 19/20 | 79.03% | 49/62
src/components/mockManagement/MockDetails/detailtoolbar |   | 79.16% | 19/24 | 100% | 0/0 | 28.57% | 2/7 | 79.16% | 19/24
src/components/mockManagement/MockDetails/detailheader |   | 84.84% | 28/33 | 35.71% | 5/14 | 42.85% | 3/7 | 84.84% | 28/33
src/components/dashboard/ContentArea/List/MockCard |   | 91.3% | 21/23 | 25% | 2/8 | 50% | 2/4 | 91.3% | 21/23
src/components/mockManagement/AddMock/AddMockForm/ResponseHeaders |   | 93.06% | 94/101 | 92.85% | 26/28 | 91.66% | 22/24 | 92.92% | 92/99
src/components/mockManagement/AddMock/AddMockForm/RequestBody |   | 93.45% | 100/107 | 92.85% | 26/28 | 92.3% | 24/26 | 93.33% | 98/105
src/components/mockManagement/AddMock/AddMockForm/RequestHeaders |   | 93.75% | 105/112 | 93.75% | 30/32 | 92.3% | 24/26 | 93.63% | 103/110

**Comment by neel1996** [comment]
<html>
<body>


File |   | Statements |   | Branches |   | Functions |   | Lines |  
-- | -- | -- | -- | -- | -- | -- | -- | -- | --
src/components/mockManagement/MockDetails |   | 36.76% | 25/68 | 10% | 1/10 | 16.66% | 3/18 | 36.76% | 25/68
src/components/mockManagement/MockDetails/detailcontentviewer |   | 46.42% | 13/28 | 14.28% | 4/28 | 50% | 1/2 | 46.42% | 13/28
src/components/dashboard/ContentArea/Sidebar |   | 51% | 51/100 | 30% | 3/10 | 38.46% | 10/26 | 52.04% | 51/98
src/utils |   | 51.35% | 19/37 | 35.71% | 5/14 | 100% | 3/3 | 51.35% | 19/37
src/components/dashboard/Toolbar |   | 52.54% | 31/59 | 8.33% | 1/12 | 80% | 4/5 | 52.54% | 31/59
src/components/dashboard |   | 53.06% | 26/49 | 0% | 0/2 | 28.57% | 4/14 | 53.06% | 26/49
src/components/dashboard/ContentArea/List |   | 53.7% | 29/54 | 10% | 3/30 | 20% | 2/10 | 54.71% | 29/53
src/hooks |   | 61.29% | 38/62 | 67.64% | 23/34 | 66.66% | 6/9 | 61.29% | 38/62
src/components/settings/PlatformSettings |   | 62.5% | 25/40 | 20% | 4/20 | 27.27% | 3/11 | 62.5% | 25/40
src/api/services/mockManagement |   | 78.68% | 48/61 | 61.36% | 27/44 | 94.73% | 18/19 | 78.68% | 48/61
src/components/mockManagement/MockDetails/detailcontentviewer/ResponsePane |   | 78.94% | 15/19 | 0% | 0/2 | 66.66% | 2/3 | 78.94% | 15/19
src/components/mockManagement/MockDetails/detailtoolbar |   | 79.16% | 19/24 | 100% | 0/0 | 28.57% | 2/7 | 79.16% | 19/24
src/components/mockManagement/MockDetails/detailheader |   | 84.84% | 28/33 | 35.71% | 5/14 | 42.85% | 3/7 | 84.84% | 28/33


</body>

**Comment by neel1996** [comment]
The existing e2e covers the missing areas which is sufficient for the existing components
