### ISSUE TITLE
🐛 [BUG] add a default logging level

### ISSUE THREAD

**Issue by jcollum-nutrien** [arbindo/mimock#174]
### What is the issue?

Easier on the user if you set a default logging level so I don't have to figure out how to set an env var for Java (a language I don't work in). 

At the least add something in documentation.md that explains how to start it with a logging level. 

```
✗ docker run mimock/mimock
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
2022-07-29 20:16:40.073 ERROR 1 --- [           main] o.s.b.d.LoggingFailureAnalysisReporter   :

***************************
APPLICATION FAILED TO START
***************************

Description:

Failed to bind properties under 'logging.level.root' to org.springframework.boot.logging.LogLevel:

    Property: logging.level.root
    Value: ${MIMOCK_LOG_LEVEL}
    Origin: class path resource [application.yml] from mimock-0.0.1.jar - 3:11
    Reason: failed to convert java.lang.String to org.springframework.boot.logging.LogLevel (caused by java.lang.IllegalArgumentException: No enum constant org.springframework.boot.logging.LogLevel.${MIMOCK_LOG_LEVEL})

Action:

Update your application's configuration. The following values are valid:

    DEBUG
    ERROR
    FATAL
    INFO
    OFF
    TRACE
    WARN
```

### Type of the bug

Backend

### Steps to reproduce

```
✗ docker run mimock/mimoc
```

### Mimock version

Don't know how to get this right now, current version in docker registry as of 29 Jul 22

### OS version

macOS 12.2.1

**Comment by neel1996** [comment]
I am setting the default LOG level to INFO and will be updating the docs with the instructions for setting other ENV variables as well.

**Comment by neel1996** [comment]
@jcollum-nutrien The default log level has been set for the app. In addition to that, the docker image now includes all the required setup to run mimock without any hassles
